[package]
name = "rust_reversi_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
indicatif = "0.17.9"

[[bin]]
name = "random_player"
path = "tests/players/random_player.rs"

[[bin]]
name = "slow_player"
path = "tests/players/slow_player.rs"
